spring:
  application:
    name: wc-fantasy-league
  datasource:
    url: jdbc:postgresql://localhost:5432/wcfantasy?options=-c%20TimeZone%3DUTC
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

jwt:
  secret: fantasy-league-super-secret-key-that-is-long-enough-256bit
  expiration: 86400000

football-api:
  key: 3e59070de9053c4ff19ab95d27f56600
  host: v3.football.api-sports.io
  league-id: 1
  season: 2026

prediction-api:
  url: http://localhost:8082
